### ISSUE TITLE
Respect different raster pixel types (point vs. area)

### ISSUE THREAD

**Issue by chambbj** [NCALM-UH/CODEM#64]
Currently, CODEM is ignoring `RasterPixelIsPoint` and `RasterPixelIsArea`. For example, registering two DSMs that are both `RasterPixelIsPoint` results in registered output that is `RasterPixelIsArea`.

The registered output should take on the pixel type of the foundation DSM.

If there is a mismatch between pixel types, any necessary shifts need to be handled internally by CODEM.

**Comment by j9ac9k** [comment]
While it doesn't look like CODEM is ignoring those attributes, it appears to compensate for them accordingly throughout the registration process. Still, perhaps the file output that is being written is not preserving what the foundation provided.

https://github.com/NCALM-UH/CODEM/blob/main/src/codem/preprocessing/preprocess.py#L157-L166

In the case of `ICP_SAVE_RESIDUALS` (which defaults to `False`) it looks like the output is written as intended?

https://github.com/NCALM-UH/CODEM/blob/main/src/codem/registration/apply.py#L208-L230

For DSM registration, here's the pdal pipeline we use to write the registered output.

https://github.com/NCALM-UH/CODEM/blob/main/src/codem/registration/apply.py#L166-L203

Indeed it appears that we do not take into consideration the area vs. point bit.

Doesn't look like there is a good way from the command line to run with ICP_SAVE_RESIDUALs (another bug or was that intentional?).  Guess you could edit this line and set to `True` and rerun.

https://github.com/NCALM-UH/CODEM/blob/main/src/codem/main.py#L323
