### ISSUE TITLE
Unequal X and Y Cell Sizes

### ISSUE THREAD

**Issue by willforker** [NCALM-UH/CODEM#9]
Currently, when a DEM is provided with X and Y cell sizes that are not equal, (even if the difference is as minute as X=11.67888888888889 and Y= 11.67888888888888) the tool fails due to `preprocess.py`, line 398, in _calculate_resolution :

`assert np.trace(A) == 0, "X scale and Y scale must be identical."`
`AssertionError: X scale and Y scale must be identical`

I have two proposals that I would like feedback on regarding how to proceed with this issue.

The much simpler proposal (but more NEGGS and ArcGIS specific) would be to add a warning in the `CODEM\arcgispro\src\coregister\esri\toolboxes\3D Data Co-Registration.pyt` file, under the `updateMessages` function, checking if the `arcpy.Describe.meanCellHeight` and `arcpy.Describe.meanCellWidth` are equal, and producing a warning if they are not. 

The other proposal would be to implement some sort of `gdal` function that would detect and modify the input data so that the X and Y cell sizes were equal prior to processing. Not sure what sort of implications this would have downstream in the processing, however. This would most likely depend on how different the X and Y cell sizes are (do people utilize rasters with non-square cells?).

Either way, curious about this issue as I have stumbled upon it both with DEMs produced from ODM as well as DEMs that were projected in ArcGIS (as CODEM doesn't like unprojected data as well).

Let me know your thoughts, happy to discuss further, thank you for reading this long message!

-Will

**Comment by hobu** [comment]
The error should be relaxed to ignore floating point mantissa, but it seems like folly for CODEM to try to figure out what to do for the true non-square pixel case (which is being fed data in a geographic coordinate system). The user should reproject their data to a cartesian coordinate system in that case. 

One could argue that CODEM could simply reproject to the appropriate UTM zone in that case, but that can be fraught. What if it is near a UTM zone boundary? Does the metadata in the reprojected file also need to be transformed in some way? It gets messy, and IMO the user should be responsible for doing what they intend instead of CODEM guessing.

**Comment by willforker** [comment]
Understood. This makes me think the best path forward would be simply a warning or error message from the toolbox if different X and Y values are detected. The option for the user to pass in an intended PCS with their input data could also be useful to save the hassle of exiting the toolbox, opening the projection tool in ArcGIS, then have to load their parameters into the CODEM toolbox again. I can begin workshopping this in the toolbox, then make a pull request.

**Comment by j9ac9k** [comment]
#14 Makes it so the restriction within codem is a bit more relaxed.  It now leverages the [Affine](https://github.com/rasterio/affine/blob/master/affine/__init__.py) built-in methods a bit more which seem to have a fudge factor of 1e-5 for many tasks.
